name: secret test 

on:
  push:
    branches:
      - master

jobs:
  secret-test:
    runs-on: ubuntu-latest

    steps:
    - name: ausgabe 
      run: 
        echo "HANS=${{secrets.MYSECRET}}" >> $GITHUB_ENV
        env
  
